yajra/laravel-datatables-html

src/Html/Builder.php
It allows me to use `->pipeline('url/to/ajax', 5)`.
For future ref. Plugin official doc can be found at:
https://datatables.net/examples/server_side/pipeline.html.
Required scripts are:
```js
//
// Pipelining function for DataTables. To be used to the `ajax` option of DataTables
//
$.fn.dataTable.pipeline = function (opts) {
// Configuration options
var conf = $.extend({
pages: 5,     // number of pages to cache
url: '',      // script url
data: null,   // function or object with parameters to send to the server
// matching how `ajax.data` works in DataTables
method: 'GET' // Ajax HTTP method
}, opts);
// Private variables for storing the cache
var cacheLower = -1;
var cacheUpper = null;
var cacheLastRequest = null;
var cacheLastJson = null;
return function (request, drawCallback, …
```
=> Datatables Pipeline Plugin support (Basic)

src/Html/Builder.php, src/Html/Column.php
this PR allow user to add custom attributes on the table header.
i think some user might be need to add custom html attributes on the header.
in my case, i need to display a tooltip when hovering on the header, so i need to add "data-toggle" attributes on the header.
it will looks like this on the view
```php
{!! $dataTable->table([], true, ['data-toggle', 'data-container', 'data-title']) !!}
```
on the datatables service class, users are able to define custom attributes on each columns.
```php
namespace App\DataTables;
use App\Models\Category;
use Yajra\Datatables\Services\DataTable;
class CategoryDataTable extends DataTable
{
// ...
/**
* Get columns.
*
* @return array
*/
protected function getColumns()
{
return [
'name' => [
'data-toggle' => 'tooltip',
'data-title' => 'Tooltip …
```
=> Configurable header attributes.

src/Html/Builder.php, src/Html/Parameters.php, tests/helper.php
Fixes php artisan serve and IE issues on long URL.
Related Issues:
https://github.com/yajra/laravel-datatables/issues/1225
https://github.com/yajra/laravel-datatables/issues/1205
https://github.com/yajra/laravel-datatables/pull/826
https://github.com/yajra/laravel-datatables/pull/671
etc..
Update html method on your service class to:
```php
/**
* Optional method if you want to use html builder.
*
* @return \Yajra\Datatables\Html\Builder
*/
public function html()
{
->minifiedAjax('')
->addAction(['width' => '80px'])
->parameters($this->getBuilderParameters());
}
```
=> Add minifiedAjax method to minify url generated when using get request.

src/Html/Builder.php
Hello,
i'm adding type GET to minifiedAjax method in Html/Builder,
because when customizing script.blade.php and using front-end thrid party tools like metronic datatable helper,
the config could be merged with a default one in the process.
The default type was POST in my case so it's not working.
I can always set this in my config, but minifiedAjax is for GET only, so i it's relevant to hard code the type of the request.
Thanks.
=> Adding type GET to minifiedAjax in Html/Builder

src/Html/Builder.php
hello,
i'm adding search headers to Html/Builder.
it will generate a second row in thead for search filters.
it's the same behaviour as drawFooter :
`$dataTable->table(['id' => 'test'], true, true)`
i don't know if it's a wanted feature or not, so it's more like a proposal.
thanks.
=> [3.0] Adding search headers to Html/Builder

composer.json
since the namespace has been changed from Datatables to DataTables
code conflict:
https://github.com/yajra/laravel-datatables/blob/b1fcc9be3403394791541ec839e1d89f3196e337/src/DataTables.php#L128
=> [2.0] Remove support for yajra/laravel-datatables-oracle v8.*

src/Html/Builder.php, tests/HtmlBuilderTest.php
This PR provides a convenient way to change table class for a certain dataTable, without touching the global configured table classes.
=> Add addTableClass, removeTableClass to Html Builder

src/Html/Builder.php, tests/HtmlBuilderTest.php, tests/helper.php
There is already a `'datatables-html.table'` configuration, and it has been merged in service provider, we can safely use it.
If someone configured incorrect attributes, failure or exception would be fine to let him easily find  out mistakes.
=> Review tableAttributes getter and setter

src/Html/Builder.php
As @herzcthu said on https://github.com/yajra/laravel-datatables-html/pull/13#issuecomment-337947000 , `minifiedAjax` does not help for a "very big" table.
I think POST ajax is common as well as GET, so I'd like to add a new method `postAjax()` to the `Html\Builder`, and `postAjax()` has the same API as `ajax()`.
```php
$builder->postAjax();
```
equals:
```php
$builder->ajax([
'type' => 'POST',
'headers' => [
'X-CSRF-TOKEN' => 'xxxxxx',
],
]);
```
- Except `type` and `method`, any other options will be merged into the final `ajax` parameter, users are free to set any options for `ajax`.
- Using an empty string for `url` is unnecessary, so I did not fill the default `url` value. If there is a reason to provide a default url, I will add it.
- Adding `X-CSRF-TOKEN` header is a safe way to …
=> Add postAjax() to Html Builder

src/Html/Builder.php
This bug prevented giving an empty array as values. I wanted to disable all buttons on a datatable by specifying `buttons => []` in the builder parameters, but it failed with this check.
=> [3.0] Fix callback check on empty values.

src/Html/Column.php, tests/HtmlBuilderTest.php
This PR adds detection of the render helper prefix as listed in the [DataTables documentation](https://datatables.net/manual/data/renderers#Built-in-helpers,) and includes a passing test for the resulting rendered JavaScript.
I'm trying to format numbers using the [DataTables built-in render helpers](https://datatables.net/manual/data/renderers#Built-in-helpers) when defining my column definitions in the model's `getColumns()` method.
When the javascript for the DataTable is generated, the helper is rendered as wrapped in a callback, instead of using the declared helper as is.
This results in the data being rendered as `[object Object]` in the table, instead of as a 2 decimal place formatted number.
```php
namespace App\DataTables;
use Yajra\DataTables\Services\DataTable;
class …
```
=> Don't wrap DataTables built in render helpers in callback

src/Html/Builder.php, src/Html/Editor.php, src/Html/Editor/Checkbox.php, src/Html/Editor/DateTime.php, src/Html/Editor/Field.php, src/Html/Editor/Hidden.php, src/Html/Editor/Password.php, src/Html/Editor/Radio.php, src/Html/Editor/ReadOnly.php, src/Html/Editor/Select.php, src/Html/Editor/TextArea.php, src/resources/config/config.php, src/resources/views/editor.blade.php
- Fix script template config key `datatables-html.script`.
- Integrate editor scripts to html builder.
- Add method to `getAjaxUrl()`.
```php
public function html()
{
->setTableId('users-table')
->minifiedAjax()
->addAction(['width' => '80px'])
->parameters($this->getBuilderParameters())
->editor($this->getEditorFields());
}
protected function getEditorFields()
{
return [
Editor\Field::make('name'),
Editor\Field::make('email'),
Editor\Password::make('password'),
Editor\Password::make('password_confirmation', 'Confirm Password'),
];
}
```
```php
public function html()
{
->setTableId('users-table')
->minifiedAjax()
->addAction(['width' => '80px']) …
```
=> [3.0] Add support for DataTables Editor script generation.

src/Html/Editor/Checkbox.php, src/Html/Editor/DateTime.php, src/Html/Editor/Field.php, src/Html/Editor/Options.php, src/Html/Editor/Select.php
- Add editor options collection builder.
- Move all setters to Field class.
- Add options source from a model or table.
```php
use Yajra\DataTables\Html\Editor;
Editor::make()
->fields([
Editor\Field::make('name'),
Editor\Field::make('email'),
Editor\Radio::make('is_admin')->options(Editor\Options::yesNo()),
]);
Editor\Radio::make('is_admin')->options(Editor\Options::trueFalse()),
Editor\Options::make()
->append('Yes', true)
->append('No', false)
->prepend('Maybe', null);
```
=> Add editor options collection builder.

src/Html/Column.php, src/Html/Editor/Boolean.php, src/Html/Editor/Date.php, src/Html/Editor/Field.php, src/Html/Editor/Number.php, src/Html/Editor/Text.php, src/Html/Editor/Time.php
- Fix field and column computed title.
From `created_at` with title `Created_At`
To `created_at` with title `Created At`
- Fix DateTime field 
- Set format to `YYYY-MM-DD hh:mm a`
- Add `military()` setter to set the time to military format.
- Boolean
- Date
- Time
- Text
- Number
=> Add new fields, fix dateTime field format.

src/Html/Options/HasData.php
-  Add ajaxWithForm api to process dataTables with form data.
- Useful for advance search.
```php
public function html()
{
->ajaxWithForm('', "#search-form") // ajax form data appended.
->dom("<'row'<'col-sm-12 col-md-6'i><'col-sm-12 col-md-6'p>>" .
"<'row'<'col-sm-12'tr>>" .
"<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'p>>")
->orderBy(0)
->searching(false)
->responsive()
->lengthMenu([10, 20, 50, 100])
->pageLength(20)
->buttons()
->columnDefs([
['responsivePriority' => 1, 'targets' => [0, 3]],
]);
}
```
=> [4.0] Add ajaxWithForm api to process dataTables with form data.

src/Html/Column.php
Currently, when the action column is added in the Builder, the render attribute is set to null, and the parseRender method is called in the Column class constructor. This commit adds a little validation to avoid calling parseRender and all the methods called inside this method.
=> [4.0] Avoid call parseRender when render attribute is null.

src/Html/HasTable.php
This is useful when the column name does not fully fit the dimensions of the column.
=> [4.0] Add title attribute for table headers.

src/Html/Builder.php, src/Html/Editor/Editor.php, src/Html/Editor/Fields/Field.php, src/resources/views/editor.blade.php, src/resources/views/options.blade.php
This PR will add an ability to generate dataTables options for external js use.
- Add undocumented / missing opts option setter.
- Add asOption api to generate dataTables scripts.
- Add toArray and toJson serializer for Editor class.
=> [4.0] Add ability to generate dataTables options for external js use.

src/Html/Editor/Editor.php
#102 fix language function to setting 'i18n' instead 'language' attribute for building Editor translation according to https://editor.datatables.net/reference/option/i18n .
=> Fix language key and use i18n.

src/Html/Button.php
Improve adding custom action to buttons.
For example I want add a button with custom action but this package not supported that. After this pull request, everybody can button with custom action using via like following code:
File: `app/Datatables/UsersDataTable.php`
```
...
public function html()
{
->setTableId('usersdatatable-table')
->minifiedAjax()
->dom('Bfrtip')
->orderBy(0)
->buttons(
(new Button)->text('Button Test')->action('alert("clicked!")')
);
}
...
```
Btw, I supported before this PR codes. So this PR not broke older codes.
=> Improve adding custom action to buttons.

src/Html/Options/HasData.php
Fix https://github.com/yajra/laravel-datatables/issues/2322.
Fix #121
=> [4.0] Use full url on ajax if not set.

src/Html/Column.php
Minor update. Some return types were hardcoded to the default Column class. This caused type hinting to break when a different class, i.e. MyColumn with some additional fluent methods, extended the Column class. Corrected by updating return types to static.
(Using version 3 on purpose for compatibility with OctoberCMS.)
=> Fixed @return types, allowing for better type hinting when the Column class is extended

src/Html/Column.php, src/Html/HasTable.php
A simple update to allow set custom HTML title instead auto-generated from "title". 
Usage:
`Column::computed('image')->title('')->htmlTitle('User image thumb');`
=> HTML title for columns labels

src/resources/views/function.blade.php
Add LaravelDataTables table variable.
See https://github.com/yajra/laravel-datatables-html/pull/143 for initial usage.
```js
mounted() {
let vm = this;
this.documentsTable = window.dtx['documents-table']({
stateSave: true,
stateSaveParams(settings, data) {
data.company_id = vm.companyId;
},
stateLoadParams(settings, data) {
vm.companyId = data.company_id;
}
})
}
```
=> Add function argument to override the default options from php scripts.

src/Html/Column.php, src/Html/ColumnDefinition.php, src/Html/ColumnDefinitions.php, src/Html/HasOptions.php, src/Html/Options/HasColumns.php, src/Html/Options/Plugins/SearchPanes.php, src/Html/SearchPane.php
Fix https://github.com/yajra/laravel-datatables/issues/2463
Fix https://github.com/yajra/laravel-datatables/issues/2471
Fix #130 
```php
// enable search panes
->searchPanes(true)
// enable search panes with array options
->searchPanes([
'viewTotal' => true,
'hideCount' => false,
])
// enable search pane with SearchPane builder class
->searchPanes(SearchPane::make()->cascadePanes(false)->hideCount())
```
=> [4.0] Add support for search panes extension.

src/Html/Column.php
To compliment https://github.com/yajra/laravel-datatables/pull/2193
```php
public function dataTable($query)
{
return datatables()
->eloquent($query)
->formatColumn('created_at', DateFormatter::class)
->setRowId('id');
}
protected function getColumns()
{
return [
Column::make('id'),
Column::formatted('created_at'),
];
}
=> Add formatted column factory.

src/Html/HasTable.php
New method to simplify fetching of table id. 
```php
$datTable->getTableAttribute('id');
```
```php
$dataTable->getTableId();
```
=> Add method getTableId()

src/Html/Editor/Fields/Field.php
This is to accept php array in def attribute of datatables.
=> Allow array on default() method

src/Html/Editor/HasEvents.php
This will allow the IDE to suggest the onClosed method when chaining in HTML Editor. 
Fixed issue with PHP stan.
=> Add onClosed Event

src/Html/Editor/HasEvents.php
This will allow the IDE to suggest the initEditor method when chaining in HTML Editor. Fixed issue with php stan.
Available since Datatables Editor 1.9.1
Reference https://editor.datatables.net/reference/event/initEditor
=> Add initEditor Event

src/Html/Editor/HasEvents.php
This will allow the IDE to suggest the onOpened method when chaining in HTML Editor. 
Fixed issue with php stan.
Available since Datatables Editor 1.9.1
Reference https://editor.datatables.net/reference/event/opened
=> Add onOpened Event

src/Html/Editor/HasEvents.php
This will allow the IDE to suggest the onPreClose method when chaining in HTML Editor. Fixed issue with php stan.
Available since Datatables Editor 1.0
Reference https://editor.datatables.net/reference/event/preClose
=> Add onPreClose Event

src/Html/Column.php
This update allows the Column exportFormat() method to accept a callable parameter to support the latest functionality in laravel-datatables-export v1.
=> feat: allow callable exportFormat parameter

src/Html/Builder.php, tests/BuilderTest.php
Set the default javascript type to `module` by setting `Builder::useVite()` in the AppServiceProvider.
```php
namespace App\Providers;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\ServiceProvider;
use Yajra\DataTables\Html\Builder;
class AppServiceProvider extends ServiceProvider
{
/**
* Register any application services.
*/
public function register(): void
{
//
}
/**
* Bootstrap any application services.
*/
public function boot(): void
{
Paginator::useBootstrapFive();
Builder::useVite();
}
}
```
=> feat: add builder ability to use viteJs by default

src/Html/Column.php
The Column::render method generates an error if the value within is too long because of path length limits of the OS.
Exception: *file_exists(): File name is longer than the maximum allowed path length on this platform (4096): /var/www/.../resources/views/{action content}*
I think 255 is a realistic length limit for view file names.
=> fix: too long file name check for column render

src/Html/Editor/Fields/DateTime.php, tests/FieldTest.php
Add missing datetime options as per https://editor.datatables.net/reference/field/datetime#Options.
=> feat: add datetime field options

src/Html/Editor/Editor.php, tests/EditorTest.php
```php
Editor::make()
->hiddenOnCreate(['is_blocked'])
->hiddenOnEdit(['password', 'password_confirmation'])
->fields([
Fields\Text::make('name'),
Fields\Text::make('email'),
Fields\Select::make('is_blocked')->options([
0 => 'No',
1 => 'Yes',
]),
Fields\Password::make('password'),
Fields\Password::make('password_confirmation'),
]),
```
=> feat: hide/show fields based on editor action

src/Html/Editor/Editor.php
```php
->formOptionsMain(FormOptions::make()->onBackground('none')),
```
=> fix: backward compatibility with FormOptions class

src/Html/Builder.php, src/Html/HasTable.php, tests/BuilderTest.php
fix: https://github.com/yajra/laravel-datatables-html/pull/169
fix: https://github.com/yajra/laravel-datatables/issues/2706
```php
public function html(): HtmlBuilder
{
->setTableId('users-table')
->addTableClass('table table-row-bordered border rounded gy-5 gs-7')
->setTableHeadClass('fw-semibold fs-6 text-gray-800')
...
```
=> feat: thead class builder

src/Html/Options/HasAjax.php
Change `url()->full()` method to `url()->current()` to solve Mixed Content when using forceScheme('https') function in Laravel
=> fix: Mixed Content problem with updating minifiedAjax method and get current url based on http or https scheme

src/Html/SearchPane.php
fix: https://github.com/yajra/laravel-datatables-docs/pull/74#issuecomment-1645043870
fix: https://github.com/yajra/laravel-datatables/pull/2475#issuecomment-1645043408
```php
->dom('PBfrtip')
->searchPanes(SearchPane::make())
```
```php
->addColumnDef([
'targets' => '_all',
'searchPanes' => SearchPane::make()
])
->buttons([Button::make('searchPanes')])
```
=> fix: show searchPanes by default

src/Html/Options/Plugins/SearchPanes.php
fix phpstan error:
```
Parameter #1 $value of method Yajra\DataTables\Html\Builder::searchPanes() expects array|bool|(callable(): mixed), Yajra\DataTables\Html\SearchPane given.
```
=> fix: add missing Arrayable param

src/Html/HtmlBuilder.php
fix: function strval expects bool|float|int|resource|string|null, mixed given.
=> fix: failing phpstan checks

src/Html/Builder.php, src/resources/views/scout.blade.php, src/resources/views/script.blade.php
See yajra/laravel-datatables#3082
Added general system to include additional js scripts to the initialization and added specific (optional) scout addition for abovementioned pull request.
Usage:
```php
public function html(): HtmlBuilder
{
->setTableId('products-table')
->addScript('datatables::scout');
}
```
=> feat: Add optional scout js script

src/resources/views/functions/batch_remove.blade.php
Now that there is a feature for additional scripts, here is a script I have been using for a long time.
Problem: When batch removing many rows via Editor, and the rows contain large amounts of data, the remove requests become slow and sometimes even fail due to server limits.
That's because Datatables adds all the column data to the remove request, which is unnecessary in most of the cases. This script modifies the data before it's sent to the server and removes all data from it except the DT_RowId, which is enough for the removal. This results in a more stable and efficient batch removal.
Usage:
```php
/**
* Optional method if you want to use the html builder.
*/
public function html(): HtmlBuilder
{
[...]
->addScript('datatables::functions.batch_remove');
}
```
=> feat: add batch remove optimization script (optional)

composer.json, src/Html/HasOptions.php, src/Html/Layout.php, tests/LayoutTest.php
ref: https://datatables.net/reference/option/layout
=> feat: layout builder

src/Html/Enums/LayoutPosition.php, src/Html/Layout.php, tests/LayoutTest.php
```php
->layout(fn (Layout $layout) => $layout->topView('#dt-toolbar'))
````
```blade
<template id="dt-toolbar">
<b>Hello World</b>
</template>
```
=> feat: load layout from view using selector

src/Html/Editor/Fields/Field.php
I had always used `->className()` on my Editor Fields without any problems, but strangely with v11.x it doesn't work anymore. Looked into the code and saw that the method never existed - so here we go!
Any idea why it worked before v11.x? Did Laravel change something on their `Fluent` class in v11?
=> feat: add className method to Editor Field

src/Html/Options/HasColumns.php, tests/BuilderTest.php
Hey Yajra hope you're doing well!
Here is the fix for the unauthorized columns being displayed in the HTML builder. I decided to simply ignore all unauthorized columns when adding columns in the HasColumns trait, that way they are completely absent from the column's collection.
Closes #222
=> Fix unauthorized columns being displayed by builder

src/Html/Editor/Editor.php
```php
Editor::macro('focusOnOpen', function (string $field) {
/** @var Editor $this */
$this->onOpen("function() { $('#DTE_Field_{$field}').focus(); }");
return $this;
});
Editor::macro('submitOnReturn', function (string|bool $action = 'submit') {
/** @var Editor $this */
$this->formOptionsMain(['onReturn' => $action]);
return $this;
});
```
```php
Editor::make()
->ajax(route('accounts.store', $this->account))
->submitOnReturn(false)
->focusOnOpen('amount')
```
=> feat: add macro in editor builder

src/Html/Button.php
fix: https://github.com/yajra/laravel-datatables/issues/3190#issuecomment-2458887426
=> Fix `Marcoable` trait usage together with `Fluent` helper

src/Html/Button.php, src/Html/Column.php, src/Html/Editor/Editor.php, src/Html/Editor/Fields/Field.php, src/Html/Editor/FormOptions.php, src/Html/Fluent.php, src/Html/Layout.php, src/Html/Parameters.php, src/Html/SearchPane.php
Fixes #229
Closes https://github.com/yajra/laravel-datatables/issues/3201
Copy Laravel's "working" `Fluent` class into this code base.
=> feat: clone the "working" `Fluent` class from laravel

phpstan.neon.dist, src/Html/Editor/Fields/Tags.php, tests/Html/Builder/BuilderOptionsLanguageTest.php, tests/Html/Builder/BuilderOptionsPluginsTest.php, tests/Html/Builder/BuilderOptionsTest.php, tests/Html/Builder/BuilderTest.php, tests/Html/Builder/LayoutTest.php, tests/Html/Builder/SearchPaneTest.php, tests/Html/Column/ColumnDefinitionTest.php, tests/Html/Column/ColumnTest.php, tests/Html/Editor/EditorFormOptionsTest.php, tests/Html/Editor/EditorTest.php, tests/Html/Editor/Fields/FieldOptionsTest.php, tests/Html/Editor/Fields/FieldTest.php, tests/Html/Editor/Fields/TagsTest.php, tests/Html/Extensions/SearchPaneTest.php
Add support for Editor 2.4.0 [tags field](https://editor.datatables.net/reference/field/tags)
```php
use Yajra\DataTables\Html\Editor\Fields\Tags;
Tags::make('permissions[].id')
->name('permissions')
->addButton('Add Permission')
->title('Permission Tags')
->noResults('No permissions found.')
->placeholder('Type to search permissions')
->inputPlaceholder('Search permissions')
->limit(2)
->label('Permissions')
->tableOptions('permissions', 'name'),
```
```php
use Yajra\DataTables\Html\Editor\Fields\Tags;
Tags::make('permissions[].id')
->name('permissions')
->addButton('Add Permission')
->title('Permission Tags')
->noResults('No permissions found.')
->placeholder('Type to search permissions')
->inputPlaceholder('Search permissions')
->limit(2)
->label('Permissions')
->ajax(),
```
```php …
```
=> feat: add tags field support

src/Html/Column.php
See: https://github.com/yajra/laravel-datatables-export/pull/71
=> fix: add missing exportRender property

composer.json, src/Html/Builder.php, src/HtmlServiceProvider.php
=> fix: change laravelcollective/html form to laravellux/html

src/HtmlServiceProvider.php
Fixed the namespace of laravellux/html HtmlServiceProvider in the import statement.
Though this is a different package, there are no changes in the namespace. 
Fixes #241
=> Fix namespace of laravellux/html HtmlServiceProvider

src/Html/Button.php, src/Html/Editor/FormOptions.php
ref: https://editor.datatables.net/reference/type/form-options#refresh
=> feat: editor refresh option

src/Html/Builder.php, tests/Html/Builder/BuilderTest.php, tests/TestComponents/test-builder-script.blade.php
This pull request allows devs to add extra template data to javascript template.
Currently, we can add extra js using addScript() method:
```php
class MyDataTableHtml extends DataTableHtml
{
public function handle(): Builder
{
return $this->getHtmlBuilder();
->addScript('inline-edit-script');
}
}
```
However, it is not possible to pass data to the template. Since the template is just a blade file, I think we should be able to do something like this:
```php
{{-- inline-edit-script.blade.php -- }}
table.on('click', 'tbody td:not(:first-child)', function (e) {
{{ $editorInstance }}.inline(this);
});
```
By allowing so, the example script could be reused on datatables that needs inline editing having $editorInstance dynamically.
With this PR, $editorInstance can be set dynamically.
```php …
```
=> feat: Allow passing data to javascript template

.github/workflows/semantic-release.yml
This pull request updates the CI/CD workflow to allow Semantic Release to be triggered manually using workflow_dispatch.
=> CI/CD: Update Semantic Release as manual run

src/Html/Options/Plugins/ColumnControl.php, tests/Html/Builder/BuilderTest.php, tests/Html/Extensions/ColumnControlTest.php
fix: [#3256](https://github.com/yajra/laravel-datatables/issues/3256)
=> fix: cc footer search
