yajra/laravel-datatables-html

composer.json
src/Html/Builder.php

Clear columns before setting new values.

Fix columns setter.

---

src/Html/Builder.php

Ex.
```php
$builder->columns(['id', 'name', 'password'])
->removeColumn('password');
```

Add method to remove column by names.

---

src/Html/Builder.php

Hello,
i have added two methods to the Builder, addBefore and addColumnBefore.
It's exactly the same logic as  add and addColumn functions, except that the new columns are prepended in the collection instead of pushed.
I think it can be useful.
thanks.

Adding addBefore and addColumnBefore in Builder

---

src/Html/Builder.php

Set default ajax url to empty string.

---

src/Html/Builder.php

Fix parsing of ajax data where function is rendered as string.

Fix parsing of ajax data.

---

src/Html/Builder.php

Fix parsing of column functions.

---

src/Html/Builder.php

Use getter to fetch table attributes.

Fix fetching of default table id from config.

---

src/Html/Builder.php

Hello,
i'm updating compileTableFooter method of Html/Builder to add the attribute functionnality.
With this PR, we can do this : 
```
'footer' => [
'title' => 'Title',
'class' => 'MyClass'
]
```
thanks.

Updating compileTableFooter of Html/Builder

---

src/Html/Builder.php

Hello,
i'm adding a check for serverSide in the minifiedAjax method in Html/Builder,
because it's not working when serverSide is false, data.columns does not exist.
thanks.

Add serverSide check to minifiedAjax in Html/Builder

---

src/Html/Builder.php

https://legacy.datatables.net/ref#fnServerData

[3.0] Add fnServerParams  to validCallbacks

---

src/Html/Builder.php

Fix column attributes: https://github.com/yajra/laravel-datatables/issues/1380

[3.0] Fix column attributes removed when generate script.

---

src/Html/Builder.php

Hello,
i'm adding generateJson method to Html/Builder and i'm changing generateScripts to use this new method.
it's allowing to recover the json config of the datatable and not the entire script, it's mainly usefull with detail table functionnality.
thanks.

[3.0] Adding generateJson to Html/Builder

---

src/Html/Builder.php

Add 'fnServerParams' to valid Callbacks

[2.0] Add fnServerParams to valid Callbacks

---

src/Html/Builder.php

remove space

---

src/HtmlServiceProvider.php

ref https://github.com/yajra/laravel-datatables/pull/1444 , https://github.com/yajra/laravel-datatables/pull/1445

[3.0] Fix HtmlServiceProvider

---

CHANGELOG.md

[3.0] Fix docs PR links.

---

README.md

Changed donation links from list to side by side image

[3.0] Remove list.

---

src/Html/Builder.php

As per PR https://github.com/yajra/laravel-datatables/pull/1105.

[3.0] Implement buttons support for editor.

---

src/Html/Builder.php

This PR will improve handling of parameters that uses a valid function callback.

Improve handling of function callbacks and better editor support.

---

src/Html/Builder.php

[3.0] Allow jQuery functions callback.

---

src/Html/Builder.php
src/resources/config/config.php

Hello,
i have moved the callback condition to config.
see https://github.com/yajra/laravel-datatables-html/issues/53 and https://github.com/yajra/laravel-datatables-html/pull/49
thanks.

[3.0] Moving callback condition to config

---

composer.json

Allow package to be installed on Laravel 5.6.

Add support for Laravel 5.6.

---

src/Html/Builder.php

Hello,
i propose this change to allow to set ajax parameters like timeout by passing and array of parameters in the last argument of minifiedAjax. I think it is usefull when you whant to customize the ajax call.
thanks.

Adding ajaxParameters to minifiedAjax

---

src/Html/Builder.php

Add parameter in addCheckbox to prepend or append the checkbox column.
When I try to add a checkbox column as the first column as following it doesn't show the checkbox column at all, if I put the `addCheckbox()` after `columns` it comes as the last column.
->addCheckbox() 

Add parameter in addCheckbox to prepend or append the checkbox column

---

composer.json

[3.0] Set min version to Laravel 5.4+

---

src/Html/Column.php

```php
protected function getColumns()
{
return [
Column::computed('action')->width(40)->title('...'),
Column::checkbox()->width(40)->title('...'),
Column::make('name'),
Column::make('email'),
Column::make('created_at'),
Column::make('updated_at'),
Column::make('id')->width(20),
];
}
```

Enhance column fluent builder.

---

composer.json

https://github.com/yajra/laravel-datatables/pull/2002

Add support for dataTables v9.0.

---

src/Html/Editor/Fields/File.php
src/Html/Editor/Fields/Image.php

In relation to https://github.com/yajra/laravel-datatables-editor/pull/38.

[4.0] Add File and Image editor fields.

---

src/Html/Button.php

Hotfix for: https://github.com/yajra/laravel-datatables-html/pull/114#issuecomment-552342243
This PR should be published immediately.

hotfix | substring to substr

---

src/Html/Button.php
src/Html/Options/Plugins/Select.php

Improve addClass method.

---

src/Html/Column.php

Add attribute responsivePriority

Set column responsive priority.

---

composer.json

Fix laravel 8 dependencies

---

src/Html/Builder.php

Allow using callbacks as a data value.

Allow using callbacks as a data value.

---

src/resources/views/editor.blade.php

Fix chrome bfcache issue with editor.

---

src/resources/views/editor.blade.php

Fix indentation.

---

src/resources/views/editor.blade.php
src/resources/views/script.blade.php

Wait for DOM before executing script using jQuery

---

README.md

Add missing version 9.x on requirements docs.

Add 9.x on requirements.

---

src/Html/Button.php

Fix https://github.com/yajra/laravel-datatables/issues/1541

Add button customize option value.

---

src/Html/Builder.php
src/resources/views/function.blade.php

This PR will add an option to wrap dataTable scripts within a function. 
```php
class EntitiesDataTableHtml extends DataTableHtml
{
public function handle()
{
return $this->setTableId('entities-table')
->orderBy(count($this->getColumns()) - 1)
->selectStyleSingle()
->responsive(false)
->buttons([
CreateButton::makeIfCan('entities-create')->text('New Entity'),
EditButton::makeIfCan('entities-update'),
RemoveButton::makeIfCan('entities-delete')->single(),
ReloadButton::make(),
])
->editors([
Editor::make()
->display('large')
->fields([
Fields\Text::make('category'),
Fields\Text::make('name'),
]),
])
// asFunction should be called last to make sure the function template is used.
->asFunction();
}
/**
* Get columns.
*
* @return array
*/
protected function …
```

Add template and method to wrap scripts with a function.

---

src/resources/config/config.php
src/resources/views/editor.blade.php
src/resources/views/function.blade.php
src/resources/views/options.blade.php
src/resources/views/script.blade.php

Make LaravelDataTables javascript namespace configurable.

---

src/Html/Editor/Fields/File.php

Full upload field options added as per https://editor.datatables.net/reference/field/upload#Options.

Add missing upload field options as per doc.

---

src/Html/Builder.php
src/Html/Editor/Editor.php
src/Html/HasEditor.php

Add method to get all editors instances.
Add method to get dataTable options array.
Set serverSide and processing option as true by default.

Fix fetching of editor table

---

src/Html/Options/HasAjax.php
tests/BuilderOptionsTest.php

- Add postAjaxWithForm
- Fix multiple form values for select and checkbox

Add postAjaxWithForm, fix multiple form values for select and checkbox

---

src/Html/Editor/Fields/Field.php

This will prevent php stan from detecting an error when using the fields nullDefault attribute.

Add nullDefault() method

---

src/Html/Options/HasAjax.php
tests/BuilderOptionsTest.php

Fix ajax form search with textarea

---

src/Html/Editor/Fields/Field.php

This will fetch and arrange enum cases to key value pair in datatables. 
Also, it help to remove custom key value pair inside your Enums.

feat: new method for enum options

---

src/Html/Options/HasAjax.php

Reverts yajra/laravel-datatables-html#186
fix: #201

Revert "fix: Mixed Content problem with updating minifiedAjax method and get current url based on http or https scheme"

---

src/Html/SearchPane.php

ref: https://datatables.net/reference/option/searchPanes.collapse

feat: add dtsp collapse option setter

---

src/Html/SearchPane.php

ref: https://datatables.net/reference/option/searchPanes.initCollapsed

feat: add initCollapsed option setter

---

src/Html/Options/Plugins/Select.php

https://datatables.net/extensions/select/examples/initialisation/keys

feat: select keyboard navigation and selection

---

src/Html/Builder.php

Fix namespace of laravellux/html in Html/Builder

---

src/Html/Builder.php

This PR adds an additional method for getting template.

feat: Add getTemplate method

---

src/Html/Builder.php

This PR adds a gate based conditional method for adding scripts.

feat: Add addScriptIfCannot method

---

src/Html/Builder.php

This PR adds a get method for additionalScripts.

feat: Add additionalscripts get method

---

src/Html/Editor/Fields/Field.php

feat: Add required functionality

---

.releaserc.yml

Updated .releaserc to refine branch rules and release behavior.

Update Semantic Release configuration
